{% set name = "foam-extend_for_pato" %}
{% set version = "4.1_2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jmeurisse/foam-extend_for_pato_conda/archive/refs/tags/{{ version }}.tar.gz
  sha256: b9d725b93798442a793ac02652eda49db9b3eca32757df035d9c96d0037c1638
  
build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - wget
    - cmake 
    - openmpi
    - coreutils
    - mercurial
    - patchelf  # [linux]
    - flex  # [linux]
    - zlib  # [linux]
    - openssh  # [linux]
    - m4  # [linux]
    - perl  # [linux]
    - boost ==1.72
    - cgal ==5.0.1
    - metis
    - scotch
    - ptscotch
    - qt
    - rpm-tools
    
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [linux]
    - wget  # [linux]
    - cmake
    - openmpi
    - coreutils
    - patchelf  # [linux]
    - flex  # [linux]
    - zlib  # [linux]
    - openssh  # [linux]
    - m4  # [linux]
    - perl  # [linux]
    - boost ==1.72
    - cgal ==5.0.1
    - metis
    - scotch
    - ptscotch
    - qt
    - rpm-tools

  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [linux]
    - wget  # [linux]
    - cmake
    - openmpi
    - coreutils
    - patchelf  # [linux]
    - flex  # [linux]
    - zlib  # [linux]
    - openssh  # [linux]
    - m4  # [linux]
    - perl  # [linux]
    - boost ==1.72
    - cgal ==5.0.1
    - metis
    - scotch
    - ptscotch
    - rpm-tools
 
extra:
  recipe-maintainers:
    - fsemerar
    - jmeurisse
