{% set name = "foam-extend_for_pato" %}
{% set version = "4.1_3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pato-devel/foam-extend_for_pato_conda/archive/refs/tags/{{ version }}_osx_arm64.tar.gz
  sha256: 7730690800cabc05d816d7962f0f34610ed49c104af740e2fab7949d098e0aa6
  
build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - sed ==4.8  # [target_platform == 'osx-64']
    - sed ==4.8  # [target_platform == 'osx-arm64']
    - boost ==1.72  # [linux]
    - boost ==1.72  # [target_platform == 'osx-64']
    - boost ==1.82  # [target_platform == 'osx-arm64']
    - {{ compiler('c') }}  # [darwin]
    - {{ compiler('cxx') }}  # [darwin]
    - gcc ==11.2.0  # [linux]
    - gxx ==11.2.0  # [linux]
    - cgal ==5.0.1  # [linux]
    - cgal ==5.0.1  # [target_platform == 'osx-64']
    - cgal ==5.6  # [target_platform == 'osx-arm64']
    - cmake ==3.23.0
    - coreutils ==9.0
    - flex ==2.6.4  # [linux]
    - m4 ==1.4.18  # [linux]
    - make ==4.3  # [linux]
    - mercurial ==6.0.3
    - metis ==5.1.0
    - openmpi ==4.1.3  # [linux]
    - openmpi ==4.1.2  # [target_platform == 'osx-64']
    - openmpi-mpicc ==4.1.6  # [target_platform == 'osx-arm64']
    - openssh ==8.9p1  # [linux]
    - patchelf ==0.14.5  # [linux]
    - perl ==5.26.2  # [linux]
    - ptscotch ==6.1.3
    - qt ==5.12.9  # [linux]
    - qt ==5.12.9  # [target_platform == 'osx-64']
    - qt ==5.15.8  # [target_platform == 'osx-arm64']
    - readline ==8.1  # [linux]
    - rpm-tools ==4.17.0  # [linux]
    - rpm-tools ==4.17.0  # [target_platform == 'osx-64']
    - scotch ==6.0.9
    - wget ==1.20.3  # [linux]
    - zlib ==1.2.11  # [linux]
    
  host:
    - sed ==4.8  # [target_platform == 'osx-64']
    - sed ==4.8  # [target_platform == 'osx-arm64']
    - boost ==1.72  # [linux]
    - boost ==1.72  # [target_platform == 'osx-64']
    - boost ==1.82  # [target_platform == 'osx-arm64']
    - {{ compiler('c') }}  # [darwin]
    - {{ compiler('cxx') }}  # [darwin]
    - gcc ==11.2.0  # [linux]
    - gxx ==11.2.0  # [linux]
    - cgal ==5.0.1  # [linux]
    - cgal ==5.0.1  # [target_platform == 'osx-64']
    - cgal ==5.6  # [target_platform == 'osx-arm64']
    - cmake ==3.23.0
    - coreutils ==9.0
    - flex ==2.6.4  # [linux]
    - m4 ==1.4.18  # [linux]
    - make ==4.3  # [linux]
    - metis ==5.1.0
    - openmpi ==4.1.3  # [linux]
    - openmpi ==4.1.2  # [target_platform == 'osx-64']
    - openmpi-mpicc ==4.1.6  # [target_platform == 'osx-arm64']
    - openssh ==8.9p1  # [linux]
    - patchelf ==0.14.5  # [linux]
    - perl ==5.26.2  # [linux]
    - ptscotch ==6.1.3
    - qt ==5.12.9  # [linux]
    - qt ==5.12.9  # [target_platform == 'osx-64']
    - qt ==5.15.8  # [target_platform == 'osx-arm64']
    - readline ==8.1  # [linux]
    - rpm-tools ==4.17.0  # [linux]
    - rpm-tools ==4.17.0  # [target_platform == 'osx-64']
    - scotch ==6.0.9
    - wget ==1.20.3  # [linux]
    - zlib ==1.2.11  # [linux]

  run:
    - sed ==4.8  # [target_platform == 'osx-64']
    - sed ==4.8  # [target_platform == 'osx-arm64']
    - boost ==1.72  # [linux]
    - boost ==1.72  # [target_platform == 'osx-64']
    - boost ==1.82  # [target_platform == 'osx-arm64']
    - {{ compiler('c') }}  # [darwin]
    - {{ compiler('cxx') }}  # [darwin]
    - gcc ==11.2.0  # [linux]
    - gxx ==11.2.0  # [linux]
    - cgal ==5.0.1  # [linux]
    - cgal ==5.0.1  # [target_platform == 'osx-64']
    - cgal ==5.6  # [target_platform == 'osx-arm64']
    - cmake ==3.23.0
    - coreutils ==9.0
    - flex ==2.6.4  # [linux]
    - m4 ==1.4.18  # [linux]
    - make ==4.3  # [linux]
    - metis ==5.1.0
    - openmpi ==4.1.3  # [linux]
    - openmpi ==4.1.2  # [target_platform == 'osx-64']
    - openmpi-mpicc ==4.1.6  # [target_platform == 'osx-arm64']
    - openssh ==8.9p1  # [linux]
    - patchelf ==0.14.5  # [linux]
    - perl ==5.26.2  # [linux]
    - ptscotch ==6.1.3
    - qt ==5.12.9  # [linux]
    - qt ==5.12.9  # [target_platform == 'osx-64']
    - qt ==5.15.8  # [target_platform == 'osx-arm64']
    - readline ==8.1  # [linux]
    - rpm-tools ==4.17.0  # [linux]
    - rpm-tools ==4.17.0  # [target_platform == 'osx-64']
    - scotch ==6.0.9
    - wget ==1.20.3  # [linux]
    - zlib ==1.2.11  # [linux]
 
extra:
  recipe-maintainers:
    - jmeurisse
