{% set name = "openfoam_for_pato" %}
{% set version = "7_2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jmeurisse/openfoam_for_pato_conda/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9ce0971ded976b604068cbe2a5eb95acc8e0a3e435ff3240062903e325baaa42
  
build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake ==3.23.0
    - coreutils ==9.0
    - flex ==2.6.4  # [linux]
    - m4 ==1.4.18  # [linux]
    - make ==4.3
    - openmpi ==4.1.3
    - openssh ==8.9p1  # [linux]
    - patchelf ==0.14.5  # [linux]
    - perl ==5.26.2  # [linux]
    - readline ==8.1  # [linux]
    - wget ==1.20.3
    - zlib ==1.2.11  # [linux]

  host:
    - boost ==1.72
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cgal ==5.0.1
    - cmake ==3.23.0
    - coreutils ==9.0
    - flex ==2.6.4  # [linux]
    - m4 ==1.4.18  # [linux]
    - make ==4.3  # [linux]
    - metis ==5.1.0
    - openmpi ==4.1.3
    - openssh ==8.9p1  # [linux]
    - patchelf ==0.14.5  # [linux] 
    - perl ==5.26.2  # [linux]
    - ptscotch ==6.1.3
    - qt ==5.12.9
    - readline ==8.1  # [linux]
    - scotch ==6.0.9
    - wget ==1.20.3  # [linux]  
    - zlib ==1.2.11  # [linux]

  run:
    - boost ==1.72
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cgal ==5.0.1
    - cmake ==3.23.0
    - coreutils ==9.0
    - flex ==2.6.4  # [linux]
    - m4 ==1.4.18  # [linux]
    - make ==4.3  # [linux]
    - metis ==5.1.0
    - openmpi ==4.1.3
    - openssh ==8.9p1  # [linux]
    - patchelf ==0.14.5  # [linux]
    - perl ==5.26.2  # [linux]
    - ptscotch ==6.1.3
    - readline ==8.1  # [linux]
    - scotch ==6.0.9
    - wget ==1.20.3  # [linux]
    - zlib ==1.2.11  # [linux]

extra:
  recipe-maintainers:
    - fsemerar
    - jmeurisse
