{% set name = "foam-extend_for_openfoam" %}
{% set version = "4.1_7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jmeurisse/foam-extend_for_openfoam_conda/archive/refs/tags/{{ version }}.tar.gz
  sha256: 38f5b0e44d2d83532681e17251fe2bdff49f8d977aa1feecea94805bad5bfa83
  
build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - wget
    - cmake 
    - openmpi
    - coreutils
    - mercurial
    - rpm-tools
    - patchelf  # [linux]
    - flex  # [linux]
    - zlib  # [linux]
    - openssh  # [linux]
    - m4  # [linux]
    - perl  # [linux]

  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [linux]
    - wget  # [linux]
    - cmake
    - openmpi
    - coreutils
    - patchelf  # [linux]
    - flex  # [linux]
    - zlib  # [linux]
    - openssh  # [linux]
    - m4  # [linux]
    - perl  # [linux]
    - boost ==1.72
    - cgal ==5.0.1
    - metis
    - scotch
    - ptscotch
    - qt
    - rpm-tools
    # - python == 3.9

  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [linux]
    - wget  # [linux]
    - cmake
    - openmpi
    - coreutils
    - patchelf  # [linux]
    - flex  # [linux]
    - zlib  # [linux]
    - openssh  # [linux]
    - m4  # [linux]
    - perl  # [linux]
    - boost ==1.72
    - cgal ==5.0.1
    - metis
    - scotch
    - ptscotch
    - rpm-tools
    # - python == 3.9
 
extra:
  recipe-maintainers:
    - fsemerar
    - jmeurisse
