{% set name = "pato" %}
{% set version = "dev" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - openfoam_for_pato ==7_2.3.1
    - foam-extend_for_pato ==4.1_3.0.0
    - tar

  host:
    - openfoam_for_pato ==7_2.3.1
    - foam-extend_for_pato ==4.1_3.0.0
    - tar

  run:
    - openfoam_for_pato ==7_2.3.1
    - foam-extend_for_pato ==4.1_3.0.0
    - tar
    
about:
  home: https://pato.ac
  license: NASA-1.3
  summary: 'A package to perform the analysis of multiphase porous reactive materials'
  description: |
    The Porous material Analysis Toolbox (PATO) is a modular analysis platform for multiphase porous 
    reactive materials. It can be run as a simple Fourier heat transfer code or include more advanced 
    features as internal decomposition (pyrolysis, vaporization), gas-gas and gas-solid chemical 
    interactions (combustion, cracking, coking), gas species transport (convection, diffusion), and 
    solid morphology evolutions (internal density changes, surface ablation). PATO is implemented as 
    a C++ top level module of the open source (GNU GPL) computational fluid dynamics software program 
    OpenFOAM. PATO also uses the open source (GNU LGPL) thermodynamics, transport, and chemistry library 
    Mutation++ produced by the von Karman Institute for Fluid Dynamics.
    <p align="center">
      <img src="http://pato.ac/wp-content/uploads/2017/06/PATO_architecture-overview.png" width="100%"></img>
    </p>
  doc_url: https://pato.ac/index.php/documentation

extra:
  recipe-maintainers:
    - fsemerar
    - jmeurisse
